In [22]:
import pandas as pd
df = pd.read_excel('/Users/kimdong-keon/Desktop/data/1.xlsx')
df

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,"지역별종별_입원실현황(단위_실, 개)_2024년1분기",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,구분상위,계,계,일반입원실,NaN,일반입원실,NaN,일반입원실,NaN,중환자실,NaN,중환자실,NaN,중환자실,NaN,격리병실,NaN,무균치료실,NaN
2,NaN,구분,계,계,일반입원실(상급),NaN,일반입원실(일반),NaN,외국인전용,NaN,중환자실_신생아,NaN,중환자실_성인,NaN,중환자실_소아,NaN,격리병실,NaN,무균치료실,NaN
3,시도,요양기관종별,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수
4,서울,상급종합병원,5520,17738,1370,1370,3699,14177,-,-,28,433,80,1165,7,98,221,293,115,202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,세종,정신병원,5,15,-,-,5,15,-,-,-,-,-,-,-,-,-,-,-,-
162,세종,의원,204,370,129,164,73,203,1,1,-,-,-,-,-,-,1,2,-,-
163,세종,치과병원,2,5,2,5,-,-,-,-,-,-,-,-,-,-,-,-,-,-
164,세종,한방병원,87,247,10,10,77,237,-,-,-,-,-,-,-,-,-,-,-,-
165,세종,한의원,29,50,6,8,23,42,-,-,-,-,-,-,-,-,-,-,-,-

In [23]:
df

,"지역별종별_입원실현황(단위_실, 개)_2024년1분기",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,구분상위,계,계,일반입원실,NaN,일반입원실,NaN,일반입원실,NaN,중환자실,NaN,중환자실,NaN,중환자실,NaN,격리병실,NaN,무균치료실,NaN
2,NaN,구분,계,계,일반입원실(상급),NaN,일반입원실(일반),NaN,외국인전용,NaN,중환자실_신생아,NaN,중환자실_성인,NaN,중환자실_소아,NaN,격리병실,NaN,무균치료실,NaN
3,시도,요양기관종별,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수,병실수,병상수
4,서울,상급종합병원,5520,17738,1370,1370,3699,14177,-,-,28,433,80,1165,7,98,221,293,115,202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,세종,정신병원,5,15,-,-,5,15,-,-,-,-,-,-,-,-,-,-,-,-
162,세종,의원,204,370,129,164,73,203,1,1,-,-,-,-,-,-,1,2,-,-
163,세종,치과병원,2,5,2,5,-,-,-,-,-,-,-,-,-,-,-,-,-,-
164,세종,한방병원,87,247,10,10,77,237,-,-,-,-,-,-,-,-,-,-,-,-
165,세종,한의원,29,50,6,8,23,42,-,-,-,-,-,-,-,-,-,-,-,-

In [19]:
# 총 20개의  columm 들

# 지역, 총병실, 총병상, 일반병실(상급), 일반병상(상급), 
# 일반병실(일반), 일반병상(일반), 외국인병실, 외국인병상,
# 중환자병실_신생아, 중환자병상_신생아, 중환자병실_성인, 중환자병상_성인, 중환자병실_소아,
# 중환자병상_소아, 격리병실, 격리병상, 무균치료실병실, 무균치료실병상
df.columns

Index(['지역별종별_입원실현황(단위_실, 개)_2024년1분기', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'],
      dtype='object')

In [24]:
df = pd.DataFrame(df)

# 0부터 2까지의 row를 삭제한 새로운 DataFrame 생성
df = df.drop(index=range(4))

# 결과 출력
df

,"지역별종별_입원실현황(단위_실, 개)_2024년1분기",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
4,서울,상급종합병원,5520,17738,1370,1370,3699,14177,-,-,28,433,80,1165,7,98,221,293,115,202
5,서울,종합병원,4347,15485,754,754,3230,13283,14,100,20,153,139,903,-,-,160,256,30,36
6,서울,병원,5241,16725,1183,1183,3987,15303,-,-,-,-,5,32,-,-,66,207,-,-
7,서울,요양병원,4571,20962,1008,1647,3455,18839,-,-,-,-,-,-,-,-,108,476,-,-
8,서울,정신병원,34,83,-,-,9,40,-,-,-,-,-,-,-,-,25,43,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,세종,정신병원,5,15,-,-,5,15,-,-,-,-,-,-,-,-,-,-,-,-
162,세종,의원,204,370,129,164,73,203,1,1,-,-,-,-,-,-,1,2,-,-
163,세종,치과병원,2,5,2,5,-,-,-,-,-,-,-,-,-,-,-,-,-,-
164,세종,한방병원,87,247,10,10,77,237,-,-,-,-,-,-,-,-,-,-,-,-
165,세종,한의원,29,50,6,8,23,42,-,-,-,-,-,-,-,-,-,-,-,-

In [12]:
new_df.columns

Index(['지역별종별_입원실현황(단위_실, 개)_2024년1분기', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'],
      dtype='object')

In [25]:
new_column_names = [
    '지역', '기관종별', '총병실', '총병상', '일반병실(상급)', 
    '일반병상(상급)', '일반병실(일반)', '일반병상(일반)', '외국인병실',
    '외국인병상', '중환자병실_신생아', '중환자병상_신생아', '중환자병실_성인', '중환자병상_성인',
    '중환자병실_소아', '중환자병상_소아', '격리병실', '격리병상', '무균치료실병실', '무균치료실병상'
]

# column 이름 변경
df.columns = new_column_names

# 결과 출력
df

,지역,기관종별,총병실,총병상,일반병실(상급),일반병상(상급),일반병실(일반),일반병상(일반),외국인병실,외국인병상,중환자병실_신생아,중환자병상_신생아,중환자병실_성인,중환자병상_성인,중환자병실_소아,중환자병상_소아,격리병실,격리병상,무균치료실병실,무균치료실병상
4,서울,상급종합병원,5520,17738,1370,1370,3699,14177,-,-,28,433,80,1165,7,98,221,293,115,202
5,서울,종합병원,4347,15485,754,754,3230,13283,14,100,20,153,139,903,-,-,160,256,30,36
6,서울,병원,5241,16725,1183,1183,3987,15303,-,-,-,-,5,32,-,-,66,207,-,-
7,서울,요양병원,4571,20962,1008,1647,3455,18839,-,-,-,-,-,-,-,-,108,476,-,-
8,서울,정신병원,34,83,-,-,9,40,-,-,-,-,-,-,-,-,25,43,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,세종,정신병원,5,15,-,-,5,15,-,-,-,-,-,-,-,-,-,-,-,-
162,세종,의원,204,370,129,164,73,203,1,1,-,-,-,-,-,-,1,2,-,-
163,세종,치과병원,2,5,2,5,-,-,-,-,-,-,-,-,-,-,-,-,-,-
164,세종,한방병원,87,247,10,10,77,237,-,-,-,-,-,-,-,-,-,-,-,-
165,세종,한의원,29,50,6,8,23,42,-,-,-,-,-,-,-,-,-,-,-,-

In [27]:
df[df['지역']=='전북']

,지역,기관종별,총병실,총병상,일반병실(상급),일반병상(상급),일반병실(일반),일반병상(일반),외국인병실,외국인병상,중환자병실_신생아,중환자병상_신생아,중환자병실_성인,중환자병상_성인,중환자병실_소아,중환자병상_소아,격리병실,격리병상,무균치료실병실,무균치료실병상
113,전북,상급종합병원,474,1897,50,50,381,1589,-,-,2,40,11,166,1,10,22,28,7,14
114,전북,종합병원,1138,3763,214,214,889,3335,-,-,1,12,12,180,-,-,22,22,-,-
115,전북,병원,1791,5873,282,282,1493,5558,-,-,-,-,-,-,-,-,16,33,-,-
116,전북,요양병원,3655,17148,596,1163,2869,15331,-,-,-,-,-,-,-,-,190,654,-,-
117,전북,정신병원,61,215,-,-,56,210,-,-,-,-,-,-,-,-,5,5,-,-
118,전북,의원,1441,3114,749,1005,692,2109,-,-,-,-,-,-,-,-,-,-,-,-
119,전북,치과의원,6,7,6,7,-,-,-,-,-,-,-,-,-,-,-,-,-,-
120,전북,보건의료원,31,104,7,10,24,94,-,-,-,-,-,-,-,-,-,-,-,-
121,전북,한방병원,844,2340,41,41,796,2292,-,-,-,-,-,-,-,-,7,7,-,-
122,전북,한의원,276,574,106,171,170,403,-,-,-,-,-,-,-,-,-,-,-,-